### ISSUE TITLE
Please provide Windows build

### ISSUE THREAD

**Issue by yarikoptic** [conda-forge/p7zip-feedstock#1]
ATM Windows is skip'ed. 
README of https://sourceforge.net/projects/p7zip/files/p7zip/16.02/ suggests that it is Windows friendly but I didn't dare to try (have no easy access to usable windows build env ATM)

**Comment by yarikoptic** [comment]
pretty please? ;-)

**Comment by scopatz** [comment]
Pull requests welcome, I am sure!

**Comment by yarikoptic** [comment]
eh, I was just ignorant in p7zip (ported 7zip for *nix) vs 7zip difference, so I guess having 7zip is good enough ;-)
